import type { Metadata } from "next";

import "./globals.css";
import { Inter, Manrope, IBM_Plex_Mono, DM_Sans, Fira_Code } from "next/font/google";
import { cn } from "@/lib/utils";

const firaCodeFiraCode = Fira_Code({subsets:['cyrillic','cyrillic-ext','greek','greek-ext','latin','latin-ext','symbols2'],weight:['300','400','500','600','700'],variable:'--font-fira-code'});

const dmSansDmSans = DM_Sans({subsets:['latin','latin-ext'],weight:['100','1000','200','300','400','500','600','700','800','900'],variable:'--font-dm-sans'});

const ibmPlexMonoIbmPlexMono = IBM_Plex_Mono({subsets:['cyrillic','cyrillic-ext','latin','latin-ext','vietnamese'],weight:['100','200','300','400','500','600','700'],variable:'--font-ibm-plex-mono'});

const manropeManrope = Manrope({subsets:['cyrillic','cyrillic-ext','greek','latin','latin-ext','vietnamese'],weight:['200','300','400','500','600','700','800'],variable:'--font-manrope'});

const interInter = Inter({subsets:['cyrillic','cyrillic-ext','greek','greek-ext','latin','latin-ext','vietnamese'],weight:['100','200','300','400','500','600','700','800','900'],variable:'--font-inter'});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased font-body",
        interInter.variable,
        ibmPlexMonoIbmPlexMono.variable,
        manropeManrope.variable,
        dmSansDmSans.variable,
        firaCodeFiraCode.variable,
      )}
    >
      <body className="min-h-full flex flex-col dark bg-[#000000]">
        {children}
      </body>
    </html>
  );
}
